### ISSUE TITLE
有的时候回自动重启 不知道为什么

### ISSUE THREAD

**Issue by oxwo** [Wmyaaa/Dell5577-hackintosh#10]
有的时候回自动重启 不知道为什么  看了下报告也没搞懂为啥   不知道你们有没有类似的情况

![111](https://user-images.githubusercontent.com/59013638/76156429-64c4c700-6135-11ea-9420-391447b9e676.png)

**Comment by Wmyaaa** [comment]
在使用触控板的时候吗。如果是触控板的话更新一下驱动😂。有时候刚开机也会因为触控板和键盘会重启。建议将Appleps2更换为voodoops2
