### ISSUE TITLE
HDMI连接显示 显示器黑屏

### ISSUE THREAD

**Issue by EasonLiuXuan** [Wmyaaa/Dell5577-hackintosh#12]
HDMI连接显示 显示器黑屏，但是系统已经识别显示器
![0AFC16A0C0AB3933FF2CE4D4BEEB413B](https://user-images.githubusercontent.com/59041834/80278681-f3fc5d00-872a-11ea-8367-64a7b6a6d3f9.png)
![23859CF0C911A11CE997844969537660](https://user-images.githubusercontent.com/59041834/80278684-f65eb700-872a-11ea-993b-8401e4643ae9.png)
，还有我的CPU是i7 7700HQ，自己修改cpufriend，然后机型设置Macbook Pro 14，3可以吗

**Comment by hiddenblue** [comment]
机型设置是没有什么问题……我原来用别的clover，花钱买了白苹果三码，改换机型，后来换到这个clover把原来三码手动提取继承了过来。CPU的问题我也在想，我也是7700hq，好像这个版本不能接近100%CPU使用。不过这样耗电量特别低，42%……损耗的电池也能用三个小时

**Comment by EasonLiuXuan** [comment]
> 最初的设置是没有什么问题……我原来用别的clover，花钱买了白苹果三码，改换型号，后来换到这个clover把原来三码手动提取继承了。想，我也是7700hq，好像这个版本不能接近100％CPU使用。不过这样耗电量特别低，42％……消耗的电池也能用三个小时

我已经修改机型为Macbook Pro 14,3,并重新制作了CPUFriend和CPUFriendDataProvider，显卡属性设置中修改id为591B0000，目前HDMI连接显示器还是不能显示

**Comment by Wmyaaa** [comment]
> > 最初的设置是没有什么问题……我原来用别的clover，花钱买了白苹果三码，改换型号，后来换到这个clover把原来三码手动提取继承了。想，我也是7700hq，好像这个版本不能接近100％CPU使用。不过这样耗电量特别低，42％……消耗的电池也能用三个小时
> 
> 我已经修改机型为Macbook Pro 14,3,并重新制作了CPUFriend和CPUFriendDataProvider，显卡属性设置中修改id为591B0000，目前HDMI连接显示器还是不能显示

情况允许的话，建议替换线材和显示器再测试，我的电脑测试了HDMI转VGA、DVI这些都没问题😂。

**Comment by IITII** [comment]
系统环境：Catalina 10.15.7 （19H15）
Opencore Release：12/07 （commit 6dc035529422f084e513170113）

HDMI 显示器无法识别，而且拔拆会导致电脑重启

**Comment by Wmyaaa** [comment]
OC没有添加HDMI的注册信息，现在还无法使用

**Comment by IITII** [comment]
fixed by  #cf1039f
