### ISSUE TITLE
楼主更新Big Sur了吗？

### ISSUE THREAD

**Issue by Fan-0104** [Wmyaaa/Dell5577-hackintosh#15]

**Comment by tzxfwan** [comment]
我更新了



---原始邮件---
发件人: "Mr.Fan"<notifications@github.com&gt;
发送时间: 2020年11月14日(周六) 上午8:24
收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)

**Comment by Fan-0104** [comment]
正式版吗？怎么更新的？在线还是覆盖安装了，昨天下午搞到现在没成功...


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: tzxfwan <notifications@github.com&gt;
发送时间: 2020年11月14日 08:47
收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&gt;
抄送: Mr.Fan <15247981124@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)





 我更新了 
 
 
 
 ---原始邮件--- 
 发件人: "Mr.Fan"<notifications@github.com&amp;gt; 
 发送时间: 2020年11月14日(周六) 上午8:24 
 收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&amp;gt;; 
 抄送: "Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)

**Comment by tzxfwan** [comment]
我是下载黑果小兵的镜像安装的



---原始邮件---
发件人: "Mr.Fan"<notifications@github.com&gt;
发送时间: 2020年11月14日(周六) 上午9:00
收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"tzxfwan"<627532785@qq.com&gt;;
主题: Re: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)




 正式版吗？怎么更新的？在线还是覆盖安装了，昨天下午搞到现在没成功... 
 
 
 发自我的iPhone 
 
 ------------------ 原始邮件 ------------------ 
 发件人: tzxfwan <notifications@github.com&amp;gt; 
 发送时间: 2020年11月14日 08:47 
 收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&amp;gt; 
 抄送: Mr.Fan <15247981124@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15) 
 
 
 
 
 
  我更新了  
   
   
   
  ---原始邮件---  
  发件人: "Mr.Fan"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年11月14日(周六) 上午8:24  
  收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&amp;amp;gt;;  
  抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;gt;;  
  主题: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)

**Comment by Fan-0104** [comment]
小冰的镜像，然后用你那个oc，我看你好像把网卡屏蔽了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: tzxfwan <notifications@github.com&gt;
发送时间: 2020年11月14日 09:04
收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&gt;
抄送: Mr.Fan <15247981124@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)





 我是下载黑果小兵的镜像安装的 
 
 
 
 ---原始邮件--- 
 发件人: "Mr.Fan"<notifications@github.com&amp;gt; 
 发送时间: 2020年11月14日(周六) 上午9:00 
 收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&amp;gt;; 
 抄送: "Comment"<comment@noreply.github.com&amp;gt;;"tzxfwan"<627532785@qq.com&amp;gt;; 
 主题: Re: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15) 
 
 
 
 
  正式版吗？怎么更新的？在线还是覆盖安装了，昨天下午搞到现在没成功...  
   
   
  发自我的iPhone  
   
  ------------------ 原始邮件 ------------------  
  发件人: tzxfwan <notifications@github.com&amp;amp;gt;  
  发送时间: 2020年11月14日 08:47  
  收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&amp;amp;gt;  
  抄送: Mr.Fan <15247981124@qq.com&amp;amp;gt;, Author <author@noreply.github.com&amp;amp;gt;  
  主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)  
   
   
   
   
   
   我更新了   
     
     
     
   ---原始邮件---   
   发件人: "Mr.Fan"<notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年11月14日(周六) 上午8:24   
   收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&amp;amp;amp;gt;;   
   抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;amp;gt;;   
   主题: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)

**Comment by tzxfwan** [comment]
我不是楼主，我的网络正常



---原始邮件---
发件人: "Mr.Fan"<notifications@github.com&gt;
发送时间: 2020年11月14日(周六) 上午9:06
收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"tzxfwan"<627532785@qq.com&gt;;
主题: Re: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)




 小冰的镜像，然后用你那个oc，我看你好像把网卡屏蔽了 
 
 
 发自我的iPhone 
 
 ------------------ 原始邮件 ------------------ 
 发件人: tzxfwan <notifications@github.com&amp;gt; 
 发送时间: 2020年11月14日 09:04 
 收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&amp;gt; 
 抄送: Mr.Fan <15247981124@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15) 
 
 
 
 
 
  我是下载黑果小兵的镜像安装的  
   
   
   
  ---原始邮件---  
  发件人: "Mr.Fan"<notifications@github.com&amp;amp;gt;  
  发送时间: 2020年11月14日(周六) 上午9:00  
  收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&amp;amp;gt;;  
  抄送: "Comment"<comment@noreply.github.com&amp;amp;gt;;"tzxfwan"<627532785@qq.com&amp;amp;gt;;  
  主题: Re: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)  
   
   
   
   
   正式版吗？怎么更新的？在线还是覆盖安装了，昨天下午搞到现在没成功...   
     
     
   发自我的iPhone   
     
   ------------------ 原始邮件 ------------------   
   发件人: tzxfwan <notifications@github.com&amp;amp;amp;gt;   
   发送时间: 2020年11月14日 08:47   
   收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&amp;amp;amp;gt;   
   抄送: Mr.Fan <15247981124@qq.com&amp;amp;amp;gt;, Author <author@noreply.github.com&amp;amp;amp;gt;   
   主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)   
     
     
     
     
     
    我更新了    
       
       
       
    ---原始邮件---    
    发件人: "Mr.Fan"<notifications@github.com&amp;amp;amp;amp;gt;    
    发送时间: 2020年11月14日(周六) 上午8:24    
    收件人: "Wmyaaa/Dell5577-hackintosh"<Dell5577-hackintosh@noreply.github.com&amp;amp;amp;amp;gt;;    
    抄送: "Subscribed"<subscribed@noreply.github.com&amp;amp;amp;amp;gt;;    
    主题: [Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)

**Comment by Wmyaaa** [comment]
> _未提供说明。_

OC引导现在是能引导bigsur的，声音(耳机需要插件)、触控板系统运行这些都是正常的。但是引导Catalina的时候触控板会不灵敏。HDMI输出目前还没测试。OC的引导来源与另一位作者，因为现在没有时间来学习OC，所以直接抄的作业。不过后期我在使用过程中会逐步优化的。

**Comment by Fan-0104** [comment]
我这里不知道什么原因引导不了，老卡磁盘被锁，楼主你顺利更新了？能讲一下你是怎么操作的吗？


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Wmyaaa <notifications@github.com&gt;
发送时间: 2020年11月14日 12:13
收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&gt;
抄送: Mr.Fan <15247981124@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)





  
未提供说明。
  
OC引导现在是能引导bigsur的，声音(耳机需要插件)、触控板系统运行这些都是正常的。但是引导Catalina的时候触控板会不灵敏。HDMI输出目前还没测试。OC的引导来源与另一位作者，因为现在没有时间来学习OC，所以直接抄的作业。不过后期我在使用过程中会逐步优化的。

**Comment by Wmyaaa** [comment]
是安装界面弹出的磁盘锁定吗还是-v跑码的时候显示的磁盘分区锁定

**Comment by Fan-0104** [comment]
-v时候显示的，用你的那个oc我都进不去格式化磁盘那里，我自己的oc是安装老重启....也不知道啥原因


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Wmyaaa <notifications@github.com&gt;
发送时间: 2020年11月14日 12:17
收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&gt;
抄送: Mr.Fan <15247981124@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)





 
是安装界面弹出的磁盘锁定吗还是-v跑码的时候显示的磁盘分区锁定

**Comment by Wmyaaa** [comment]
是卡在哪里了吗，比如跑马的时候到哪一步就卡住了

**Comment by Wmyaaa** [comment]
你用的什么网卡啊，1560？

**Comment by Fan-0104** [comment]
我的那个oc不卡，很顺利，然后就重启了


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Wmyaaa <notifications@github.com&gt;
发送时间: 2020年11月14日 12:27
收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&gt;
抄送: Mr.Fan <15247981124@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)





 
是卡在哪里了吗，比如跑马的时候到哪一步就卡住了

**Comment by Fan-0104** [comment]
1820a


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Wmyaaa <notifications@github.com&gt;
发送时间: 2020年11月14日 12:29
收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&gt;
抄送: Mr.Fan <15247981124@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)





 
你用的什么网卡啊，1560？

**Comment by Fan-0104** [comment]
能发一下QQ什么的嘛？邮件比较麻烦……


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Wmyaaa <notifications@github.com&gt;
发送时间: 2020年11月14日 12:29
收件人: Wmyaaa/Dell5577-hackintosh <Dell5577-hackintosh@noreply.github.com&gt;
抄送: Mr.Fan <15247981124@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[Wmyaaa/Dell5577-hackintosh] 楼主更新Big Sur了吗？ (#15)





 
你用的什么网卡啊，1560？

**Comment by Wmyaaa** [comment]
546457267

**Comment by tonylu110** [comment]
> > _未提供说明。_
> 
> OC 引导现在是能引导 bigsur 的，声音 (耳机需要插件)、触控板系统运行这些都是正常的。但是引导 Catalina 的时候触控板会不灵敏。HDMI 输出目前还没测试。OC 的引导来源与另一位作者，因为现在没有时间来学习 OC，所以直接抄的作业。不过后期我在使用过程中会逐步优化的。

耳机啥插件

**Comment by Wmyaaa** [comment]
alc256
