### ISSUE TITLE
跑代码

### ISSUE THREAD

**Issue by wlhpc12138** [Wmyaaa/Dell5577-hackintosh#17]
出苹果标志跑代码，关机也有，百度教程删除了-v，然后连启动项都不显示了，有啥方法吗？

**Comment by Wmyaaa** [comment]
是booter那删除的吗，有个是-V 还有有个是-Vsmalldate哦

**Comment by wlhpc12138** [comment]
好像是boot args里面的

**Comment by Wmyaaa** [comment]
启动项都不显示了是什么意思喃

**Comment by wlhpc12138** [comment]
OC只显示windows，不会显示Macintosh HD
