### ISSUE TITLE
BCM94360cs2不是台式机的网卡吗？

### ISSUE THREAD

**Issue by entercoder1993** [Wmyaaa/Dell5577-hackintosh#2]
你是怎么换的？

**Comment by Wmyaaa** [comment]
> 你是怎么换的？

把网卡那一块的空间再打磨了一下好放置转接卡。😂

**Comment by tzxfwan** [comment]
我已经弄好了，网卡啥的没什么问题，并且已经升级到最高版本的系统了。------------------ 原始邮件 ------------------
发件人: "Wmyaaa"<notifications@github.com>
发送时间: 2019年6月11日(星期二) 中午11:21
收件人: "Wmyaaa/Dell5577-hackintosh-clover"<Dell5577-hackintosh-clover@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: Re: [Wmyaaa/Dell5577-hackintosh-clover] BCM94360cs2不是台式机的网卡吗？ (#2)


 
你是怎么换的？
  
把网卡那一块的空间再打磨了一下好放置转接卡。
 
&mdash;

**Comment by TianQuanxing1** [comment]
真是狼灭

**Comment by hiddenblue** [comment]
太强了……我选择直接淘宝160买了一块博通的笔记本卡
