### ISSUE TITLE
Brightness keys not working.

### ISSUE THREAD

**Issue by priyanshuarora595** [Wmyaaa/Dell5577-hackintosh#20]
I am using clover 15.1 and brightness keys are not working in it. Everything else is working great , audio, HDMI , graphics and all.... Please tell me how to fix brightness keys....
Thanks

**Comment by Wmyaaa** [comment]
Screen brightness is driven, but not added to the default FN function key. You can set the shortcut key for the brightness of the screen in preferences keyboard shortcut keys

**Comment by priyanshuarora595** [comment]
> Screen brightness is driven, but not added to the default FN function key. You can set the shortcut key for the brightness of the screen in preferences keyboard keyboard keys

screen brightness is also not driven in preference . i tried that...

**Comment by priyanshuarora595** [comment]
Just updated to opencore big sur.  Everything working now , thank you
