### ISSUE TITLE
昨天发的efi报错

### ISSUE THREAD

**Issue by qq974708586** [Wmyaaa/Dell5577-hackintosh#22]
![1607398010637](https://user-images.githubusercontent.com/66658523/101435996-f46cf100-38d2-11eb-80b7-28f6c737ff5d.jpg)
开机按f12找不到U盘的efi，然后如果用好的efi能找到U盘的efi（就是下载你的最新的efi），然后启动下载你的efi报OCB:StartImage failed - Already started
但是按照网上说的解决方案还是不行，具体的没明白什么问题

**Comment by Wmyaaa** [comment]
之前发的EFI没有报这错吗

**Comment by qq974708586** [comment]
11月8号发的，我下载的那个bigsur.oc.zip那个文件安装及启动不报错（后来我看了一下还有一个名为opencore.zip的压缩包，没试），除了声音驱动、HDMI外，其他好像都是正常的（目前没发现这两个外其他的）

**Comment by Wmyaaa** [comment]
然后昨天发的包就出现这问题了吗😂

**Comment by qq974708586** [comment]
是的，我也很奇怪，我使用beyond compare对比，感觉不应该出现这个问题，太神奇了😂😂😂

**Comment by Wmyaaa** [comment]
你把12/7kext那个文件夹和11/8那个做下替换喃

**Comment by Wmyaaa** [comment]
加个QQ吧，晚上帮你弄下
