### ISSUE TITLE
请问各位前辈，各位的occ能够打开配置文件吗？

### ISSUE THREAD

**Issue by yangfanjie97** [Wmyaaa/Dell5577-hackintosh#26]
系统（黑果小兵）：macOS BigSur 11.1 20C69
oc版本： 0.63（0.64打开提示版本过高）（occ好像是2.17）

当挂载分区后，config.plist 使用occ打开无反应
请问一下各位前辈们有没有遇到过这个问题？改如何解决？

**Comment by Wmyaaa** [comment]
意思是config无法编辑吗

**Comment by yangfanjie97** [comment]
是的！使用occ打开config.plist 是没有响应的（occ不会卡死）。  使用低版本的occ（例如2.15）挂载efi分区occ就会卡死。必须退出，重新打开才行。
请问一下有没有替代occ的工具。没有的话，只能够回退到15.7了。
最后，非常感谢您的开源。

**Comment by Wmyaaa** [comment]
建议用命令行终端挂载efi试试，然后把oc文件夹拖到桌面编辑呢

**Comment by yangfanjie97** [comment]
问题解决了。可能是occ的低版本不兼容macOS BigSur 11.1 20C69， 所以我使用了oc（6.4）对应的occ（大概是2.18）。
目前原生网卡可以正常使用（使用 itlwm 驱动 ）。日常体验上没有问题！
最后，再次感谢您的开源！
