### ISSUE TITLE
是否需要添加手动安装 BigSur 教程到 README?

### ISSUE THREAD

**Issue by IITII** [Wmyaaa/Dell5577-hackintosh#29]
* 本人编写了一个在 `Dell 5577` 上 **手动安装** `BigSur` 的教程，但是我不清楚到底要不要提 `PR`，所以特地来问问

[https://iitii.github.io/2021/01/24/1/](https://iitii.github.io/2021/01/24/1/)

**Comment by Wmyaaa** [comment]
啥意思😂，没太明白

**Comment by IITII** [comment]
简单点说就是，为了方便黑果，我写了个教程。
你看看需不需要加到README 里面去。
（顺带一提，之前的 PR(Pull Request) 是不是也该看看了

**Comment by Wmyaaa** [comment]
你可以Fork一份过去噻，或者用码云添加了可以自动更新库。PR不是上了么。"不太会弄Github的功能😂"

**Comment by Wmyaaa** [comment]
看要怎么添上，或许可以建个群
