### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by tzxfwan** [Wmyaaa/Dell5577-hackintosh#3]
今晚上想安装一下不知道您方不方便在线指导一下，可以加QQ好友627532785

**Comment by Wmyaaa** [comment]
> 今晚上想安装一下不知道您方不方便在线指导一下，可以加QQ好友627532785
请问是那一块问题呢。

**Comment by tzxfwan** [comment]
我觉得我估计会遇到问题，然而并没有很顺利😂------------------ 原始邮件 ------------------
发件人: "Wmyaaa"<notifications@github.com>
发送时间: 2019年6月11日(星期二) 中午11:25
收件人: "Wmyaaa/Dell5577-hackintosh-clover"<Dell5577-hackintosh-clover@noreply.github.com>;
抄送: "tzxfwan"<627532785@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Wmyaaa/Dell5577-hackintosh-clover] 求助 (#3)


 
今晚上想安装一下不知道您方不方便在线指导一下，可以加QQ好友627532785
 请问是那一块问题呢。
  
&mdash;

**Comment by Wmyaaa** [comment]
我加你了
