### ISSUE TITLE
big sur on dell 5577

### ISSUE THREAD

**Issue by priyanshuarora595** [Wmyaaa/Dell5577-hackintosh#31]
can anyone please share working EFI folder for MacOS Big Sur for dell inspiron 15 5577 laptop.
i am always facing black screen issue and i am unable to install big sur. 
thank you.

**Comment by IITII** [comment]
Just download the latest release. It works well on my machine(HDMI is supported). @priyanshuarora595 

https://github.com/Wmyaaa/Dell5577-hackintosh/releases/download/%E9%BC%A0%E5%B9%B4%E5%AE%8C%E7%BB%93%E7%89%88/default.zip

**Comment by priyanshuarora595** [comment]
> Just download the latest release. It works well on my machine(HDMI is supported). @priyanshuarora595
> 
> https://github.com/Wmyaaa/Dell5577-hackintosh/releases/download/%E9%BC%A0%E5%B9%B4%E5%AE%8C%E7%BB%93%E7%89%88/default.zip

Shows black screen when trying to boot from it. 
Please provide solution for it.

**Comment by IITII** [comment]
I can not give any useful suggestion to you(@priyanshuarora595) without your steps for `Install Big Sur`.
Please show it to us.(Screenshots are much better)

> You can also refer to this link: [https://iitii.github.io/2021/01/24/1/](https://iitii.github.io/2021/01/24/1/)  
> Please using Google Translate or others if you have some reading trouble.

**Comment by priyanshuarora595** [comment]
> I can not give any useful suggestion to you(@priyanshuarora595) without your steps for `Install Big Sur`.
> Please show it to us.(Screenshots are much better)
> 
> > You can also refer to this link: https://iitii.github.io/2021/01/24/1/
> > Please using Google Translate or others if you have some reading trouble.

[https://drive.google.com/file/d/1SoP-wOUInL3n2RXMkgx4TdfUgK_KdPcY/view?usp=sharing](url)
here is the video. please check it once

**Comment by IITII** [comment]
Looks like there are some problems with your BIOS settingsand usb bootable devices.
@priyanshuarora595 


> MacOS do not support `legacy boot loader`  

1. BIOS -> BOOT -> UEFI, using `UEFI` as boot loader type and set `Security Boot` to disable

![image](https://user-images.githubusercontent.com/33705067/112952849-87c27e80-916f-11eb-846c-d5aa6fb69996.png)

**Comment by priyanshuarora595** [comment]
> Looks like there are some problems with your BIOS settingsand usb bootable devices.
> @priyanshuarora595
> 
> > MacOS do not support `legacy boot loader`
> 
> 1. BIOS -> BOOT -> UEFI, using as boot loader type and set to disable`UEFI``Security Boot`
> 
> ![image](https://user-images.githubusercontent.com/33705067/112952849-87c27e80-916f-11eb-846c-d5aa6fb69996.png)

no success
tried it already

**Comment by IITII** [comment]
There are some possible reasons.

* BIOS Setting is wrong. ( Set `UEFI mode` and disable `Security Boot`)
* The partition of your removable disk is wrong. ( GPT partition, please create bootable devices via offical images and tools )

@priyanshuarora595

**Comment by priyanshuarora595** [comment]
> There are some possible reasons.
> 
> * BIOS Setting is wrong. ( Set `UEFI mode` and disable `Security Boot`)
> * The partition of your removable disk is wrong. (GPT partition, please create bootable devices via offical images and tools)
> 
> @priyanshuarora595

Boot mode is set to UEFI nad secure boot is already disabled . I am running macOS catalina on my hard drive already. And i created usb from catalina only , it is formatted in gpt partition

**Comment by IITII** [comment]
Have you copy the OC files to bootable device's EFI partition?

**Comment by priyanshuarora595** [comment]
> Have you copy the OC files to bootable device's EFI partition?

Yes , that's how i was was able to boot and get this verbose

**Comment by IITII** [comment]
Now let's remove all the unstable factors.
Remove your disk which Catalina is installed, and try boot again.

**Comment by priyanshuarora595** [comment]
> Now let's remove all the unstable factors.
> Remove your disk which Catalina is installed, and try boot again.

But how dos that affect booting usb ?

**Comment by IITII** [comment]
You can see `external` after `Install Big Sur` which means the boot loader using the OC files on your hard drive not removable devices.
So that is why I suggest you to remove your hard drive and try again.

**Comment by priyanshuarora595** [comment]
> You can see `external` after `Install Big Sur` which means the boot loader using the OC files on your hard drive not removable devices.
> So that is why I suggest you to remove your hard drive and try again.

But that is showing external because i am installing from external usb . How will that change if i remove hard disk....

**Comment by IITII** [comment]
It will not show if you have only one bootable devices. Just try it

**Comment by priyanshuarora595** [comment]
> It will not show(only `Install ***`) if you have only one bootable devices. Just try it

okay let me try it.

**Comment by priyanshuarora595** [comment]
> It will not show(only `Install ***`) if you have only one bootable devices. Just try it

I tried it but got no success . 
Just tell me that , are you running macOS bigsur on dell 5577 laptop i5 processor ? 
Also , can you please share an image of your config.plist which shows the device properties of your display configuration (the platform id and device id ) that will be really helpful.

**Comment by IITII** [comment]
![image](https://user-images.githubusercontent.com/33705067/113436492-5ff54400-9417-11eb-92a0-286694491b85.png)

![image](https://user-images.githubusercontent.com/33705067/113436595-959a2d00-9417-11eb-9156-971e3dc64965.png)

**Comment by priyanshuarora595** [comment]
I changed device id to 16190000 and it booted with viable screen but now its stuck with apple logo and saying " less than a minute remaining" what should i do now??? 
@IITII

**Comment by priyanshuarora595** [comment]
Now i have installed macos bigsur but I'm unable to boot . I'm stuck at waiting for DSMOS what to do now???
![IMG_20210402_235506](https://user-images.githubusercontent.com/57026241/113444689-02aac400-9412-11eb-8acc-b3bbb7c62c3b.jpg)

**Comment by IITII** [comment]
* Where is your removable drive which you use to install macos when booting your computer?
* Have you copy the oc files to the efi partition of disk which bigsur installed after system install

**Comment by priyanshuarora595** [comment]
> > take care of 4 and 5 lines of logs on your screen shot.
> 
> * Where is your removable drive which you use to install macos when booting your computer?
> * Have you copy the oc files to the efi partition of disk which bigsur installed after system install

I booted from installation usb only..... It's some graphics issue maybe

**Comment by priyanshuarora595** [comment]
@IITII 

Now this is what i am facing 
![IMG_20210403_224514](https://user-images.githubusercontent.com/57026241/113486024-5975d380-94ce-11eb-8eda-cfd83015522f.jpg)

My own laptop screen is not showing anything but if i attach it to hdmi monitor , its working fine with full hardware acceleration 2gb graphics.... How to solve this ??? Please help

**Comment by IITII** [comment]
Reboot.
Turn to @Wmyaaa  if the screen is still showing nothing after multiple reboot.

> It's normal when graphics card is `Intel Iris Plus Graphics 650 2048 MB`  

Good luck! @priyanshuarora595

**Comment by priyanshuarora595** [comment]
> Reboot.
> Turn to @Wmyaaa if the screen is still showing nothing after multiple reboot.
> 
> > It's normal when graphics card is `Intel Iris Plus Graphics 650 2048 MB`
> 
> Good luck! @priyanshuarora595

I tried booting multiple times but facing same issue , hdmi working but main laptop screen stays black....

What do you mean by 
It's normal when graphics card is `Intel Iris Plus Graphics 650 2048 MB` ?????
How do i fix it?

**Comment by priyanshuarora595** [comment]
> Reboot.
> Turn to @Wmyaaa if the screen is still showing nothing after multiple reboot.
> 
> > It's normal when graphics card is `Intel Iris Plus Graphics 650 2048 MB`
> 
> Good luck! @priyanshuarora595

i have INTEL HD GRAPHICS 630 . but the config.plist has set graphics to Intel Iris Plus Graphics 650 . if i go to boot from configGPU.plist . it never boots i dont know why... 
i am really close to get big sur working on my laptop please help me .

i have intel HD graphics 630 , dell inspiron 15 5577 i5 laptop. please help @IITII @Wmyaaa

**Comment by priyanshuarora595** [comment]
> Reboot.
> Turn to @Wmyaaa if the screen is still showing nothing after multiple reboot.
> 
> > It's normal when graphics card is `Intel Iris Plus Graphics 650 2048 MB`
> 
> Good luck! @priyanshuarora595

Can you please send your efi folder please
That will be really helpful 
Thank you.

**Comment by IITII** [comment]
Here you are 
[EFI.zip](https://github.com/Wmyaaa/Dell5577-hackintosh/files/6254978/EFI.zip)

* By the way, please pay attention to file folder structure. `EFI Partition` -> `EFI Folder` -> `OC Folder`

![image](https://user-images.githubusercontent.com/33705067/113515728-e0977a00-95a8-11eb-877c-93ac140bd45b.png)

**Comment by priyanshuarora595** [comment]
> Here you are
> [EFI.zip](https://github.com/Wmyaaa/Dell5577-hackintosh/files/6254978/EFI.zip)
> 
> * By the way, please pay attention to file folder structure. `EFI Partition` -> `EFI Folder` -> `OC Folder`
> 
> ![image](https://user-images.githubusercontent.com/33705067/113515728-e0977a00-95a8-11eb-877c-93ac140bd45b.png)

Yes i am also following this exact same structure . Thank you so much. I'll try your efi folder . Thank you.

**Comment by priyanshuarora595** [comment]
> Here you are. It is no different from the latest release, except for itlwm support.
> 
> [EFI.zip](https://github.com/Wmyaaa/Dell5577-hackintosh/files/6254978/EFI.zip)
> 
> * By the way, please pay attention to file folder structure. `EFI Partition` -> `EFI Folder` -> `OC Folder`
> 
> ![image](https://user-images.githubusercontent.com/33705067/113515728-e0977a00-95a8-11eb-877c-93ac140bd45b.png)

I am still facing same issue.... I cant understand why is it happening if we both have exactly same device. 


Same issue , laptop screen not working but hdmi is working.

**Comment by priyanshuarora595** [comment]
> Here you are. It is no different from the latest release, except for itlwm support.
> 
> [EFI.zip](https://github.com/Wmyaaa/Dell5577-hackintosh/files/6254978/EFI.zip)
> 
> * By the way, please pay attention to file folder structure. `EFI Partition` -> `EFI Folder` -> `OC Folder`
> 
> ![image](https://user-images.githubusercontent.com/33705067/113515728-e0977a00-95a8-11eb-877c-93ac140bd45b.png)

Have you ever replaced your screen???  What could be the reason that your device is supporting internal display but mine is not.... ?
I'm stuck please guide @IITII  @Wmyaaa  @wgggSg

**Comment by priyanshuarora595** [comment]
@IITII @Wmyaaa 

If i use platform id as 00001659 and device id as 16590000

I get graphics acceleration but on hdmi external monitor and not on internal laptop screen

But if i use platform id 00001659 with device id 16190000 , i get no hardware acceleration but internal display works (with much lag) and hdmi doesn't work

Can this be helpful in finding the issue???

Please respond . I need this to get fixed anyhow.

**Comment by IITII** [comment]
Turn to @Wmyaaa if you (@priyanshuarora595 ) have any problem about OC configure.

I just use the last release and install bigsur follow the steps in this [blog](https://iitii.github.io/2021/01/24/1/). Everything goes will.

Sorry.

**Comment by priyanshuarora595** [comment]
> Turn to @Wmyaaa if you (@priyanshuarora595 ) have any problem about OC configure.
> 
> I just use the last release and install bigsur follow the steps in this [blog](https://iitii.github.io/2021/01/24/1/). Everything goes will.
> 
> Sorry.

Okay 😞😞😞😞

**Comment by priyanshuarora595** [comment]
Got it working

Just try this device properties :

AAPL,ig-platform-id
AAAbGQ==
device-id
FhkAAA==
disable-external-gpu
AQAAAA==
enable-hdmi20
AQAAAA==
framebuffer-con1-enable
AQAAAA==
framebuffer-con1-type
AAgAAA==
framebuffer-con2-busid
AAAAAA==
framebuffer-con2-enable
AQAAAA==
framebuffer-con2-flags
AAAAAA==
framebuffer-con2-index
/////w==
framebuffer-con2-pipe
AAAAAA==
framebuffer-con2-type
AQAAAA==
framebuffer-con3-enable
AQAAAA==
framebuffer-con3-flags
AAAAAA==
framebuffer-fbmem
AACQAA==
framebuffer-memorycount
AwAAAA==
framebuffer-patch-enable
AQAAAA==
framebuffer-pipecount
AwAAAA==
framebuffer-portcount
AwAAAA==
framebuffer-stolenmem
AAAwAQ==
framebuffer-unifiedmem
AAAAgA==
model
Intel HD Graphics 630

with boot args : -disablegfxfirmware lilucpu=8

Thank you

**Comment by Vishnu-peringhatt** [comment]
> 

hello, i'm extremely new on the scene, could please clarify exactly where i should type the "boot args"

**Comment by priyanshuarora595** [comment]
> > 
> 
> hello, i'm extremely new on the scene, could please clarify exactly where i should type the "boot args"

in your config.plist , there is a section by the name of NVRAM. There  you'll see boot-args
![image](https://user-images.githubusercontent.com/57026241/181682400-fe885e3b-c7a7-4f4b-900a-effc7b62d879.png)

**Comment by Vishnu-peringhatt** [comment]
Thank you, if it's not inconvenience for you could you please share your EFI folder with me?

should i add the lines(which you pointed out in you previous post) who aren't present in config.plist?

**Comment by priyanshuarora595** [comment]
> Thank you, if it's not inconvenience for you could you please share your EFI folder with me?
> 
> should i add the lines(which you pointed out in you previous post) who aren't present in config.plist?
> 
> How should i edit the .plist file i'm currently using vs code and proper tree app in windows ( i don't know how to add new lines into the file using proper tree app?, the data values provided by you and the what shown in property app doesn't match like there in diff format? language ? or something) I currently reached where the verbose get finished then a dark screen is shown what should i do? sorry for the long post, and thank you for the fast reply.
> 
> (I'm using the same device as you "inspiron Gaming 5577" and installing Big sur on system with just windows using Big Sur recovery file [config.zip](https://github.com/Wmyaaa/Dell5577-hackintosh/files/9217602/config.zip) ) i have added my config file for referrence and i'm using the lastest EFI folder from the master archiev of from this [https://github.com/Wmyaaa/Dell5577-hackintosh](url) Just copied the BIG sur folder to EFI of my pendrive

You can't edit using vscode . you need proper tree to edit the config.plist and in the boot-agrs you need to provide the arguments I gave in previous comment. 
I can't share my EFI folder. 
I can just edit your config file if you want. But for that too I need some time because I'm busy with some stuff right now.

**Comment by Vishnu-peringhatt** [comment]
If it's not too much thank you for your help.
While editing i noticed that 
Eg :
What you gave
AAPL,ig-platform-id
AAAbGQ==

What I saw in the prope tree app

AAPL,ig-platform-id       data      00001B59

it looked like they were using different languages something or am i wrong? like can i just type "AAAbGQ=="
in the value section of property app for "AAPL,ig-platform-id" with "data" as the type?

And if possible please edit the config file for me and do take you time

**Comment by Vishnu-peringhatt** [comment]
> > Thank you, if it's not inconvenience for you could you please share your EFI folder with me?
> > should i add the lines(which you pointed out in you previous post) who aren't present in config.plist?
> > How should i edit the .plist file i'm currently using vs code and proper tree app in windows ( i don't know how to add new lines into the file using proper tree app?, the data values provided by you and the what shown in property app doesn't match like there in diff format? language ? or something) I currently reached where the verbose get finished then a dark screen is shown what should i do? sorry for the long post, and thank you for the fast reply.
> > (I'm using the same device as you "inspiron Gaming 5577" and installing Big sur on system with just windows using Big Sur recovery file [config.zip](https://github.com/Wmyaaa/Dell5577-hackintosh/files/9217602/config.zip) ) i have added my config file for referrence and i'm using the lastest EFI folder from the master archiev of from this [https://github.com/Wmyaaa/Dell5577-hackintosh](url) Just copied the BIG sur folder to EFI of my pendrive
> 
> You can't edit using vscode . you need proper tree to edit the config.plist and in the boot-agrs you need to provide the arguments I gave in previous comment. I can't share my EFI folder. I can just edit your config file if you want. But for that too I need some time because I'm busy with some stuff right now.

I successfully installed the os  the only problem is I can't access the wifi and Bluetooth could you please help me?

**Comment by priyanshuarora595** [comment]
> > > Thank you, if it's not inconvenience for you could you please share your EFI folder with me?
> > > should i add the lines(which you pointed out in you previous post) who aren't present in config.plist?
> > > How should i edit the .plist file i'm currently using vs code and proper tree app in windows ( i don't know how to add new lines into the file using proper tree app?, the data values provided by you and the what shown in property app doesn't match like there in diff format? language ? or something) I currently reached where the verbose get finished then a dark screen is shown what should i do? sorry for the long post, and thank you for the fast reply.
> > > (I'm using the same device as you "inspiron Gaming 5577" and installing Big sur on system with just windows using Big Sur recovery file [config.zip](https://github.com/Wmyaaa/Dell5577-hackintosh/files/9217602/config.zip) ) i have added my config file for referrence and i'm using the lastest EFI folder from the master archiev of from this [https://github.com/Wmyaaa/Dell5577-hackintosh](url) Just copied the BIG sur folder to EFI of my pendrive
> > 
> > 
> > You can't edit using vscode . you need proper tree to edit the config.plist and in the boot-agrs you need to provide the arguments I gave in previous comment. I can't share my EFI folder. I can just edit your config file if you want. But for that too I need some time because I'm busy with some stuff right now.
> 
> I successfully installed the os the only problem is I can't access the wifi and Bluetooth could you please help me?

really very sorry for the delay.
you should use intel wifi kext according to you wifi chip.

https://www.youtube.com/watch?v=ii2ZEPJ2lzg

this might help
