### ISSUE TITLE
ConfigGPU.plist

### ISSUE THREAD

**Issue by priyanshuarora595** [Wmyaaa/Dell5577-hackintosh#35]
What is this configGPU.plist ???
What is different in it from config.plist ???
Please explain. @Wmyaaa

**Comment by symabbas** [comment]
hey man, use this EFI: https://drive.google.com/drive/folders/1tOi-7Th22Pw47frt7mbYaLF9wesqnKDV?usp=sharing

**Comment by priyanshuarora595** [comment]
> hey man, use this EFI: https://drive.google.com/drive/folders/1tOi-7Th22Pw47frt7mbYaLF9wesqnKDV?usp=sharing

Okay... Let me try this

**Comment by priyanshuarora595** [comment]
> hey man, use this EFI: https://drive.google.com/drive/folders/1tOi-7Th22Pw47frt7mbYaLF9wesqnKDV?usp=sharing

Still same man.... Blank screen , brightness and volume working fine.... But nothing on screen .. .
![IMG_20210406_130707](https://user-images.githubusercontent.com/57026241/113675487-09b72800-96d9-11eb-87e2-64cd2509baca.jpg)

**Comment by symabbas** [comment]
what do you mean volume and sound keys are working?
is the dialog displaying ?

**Comment by symabbas** [comment]
May be try a reinstall from the recovery option

**Comment by symabbas** [comment]
what are your bios settings?

**Comment by priyanshuarora595** [comment]
> what do you mean volume and sound keys are working?
> is the dialog displaying ?

No.... I blindly logged in my account and tried to change volume and brightness from keys.... And it responded

Also , HDMI is  working but not the main screen
![16176949741943353586318461339770](https://user-images.githubusercontent.com/57026241/113676236-d1fcb000-96d9-11eb-830b-d978f60d58b3.jpg)

**Comment by symabbas** [comment]
that's strange. Check the display settings

**Comment by priyanshuarora595** [comment]
> what are your bios settings?

![IMG_20210406_073148](https://user-images.githubusercontent.com/57026241/113676307-ea6cca80-96d9-11eb-807d-fe6a9e3d01c0.jpg)


![IMG_20210406_073217](https://user-images.githubusercontent.com/57026241/113676317-eccf2480-96d9-11eb-969d-50b5365010c7.jpg)ab
![IMG_20210406_073203](https://user-images.githubusercontent.com/57026241/113676319-ed67bb00-96d9-11eb-8423-4f11da1d86e1.jpg)

I have disabled virtualization and vt for direct I/O

**Comment by priyanshuarora595** [comment]
> that's strange. Check the display settings

Where to check?

**Comment by symabbas** [comment]
normal mac os settings

**Comment by priyanshuarora595** [comment]
> normal mac os settings



> normal mac os settings

![16176953207641632626729671301875](https://user-images.githubusercontent.com/57026241/113676924-a29a7300-96da-11eb-9a56-169e2d4450b6.jpg)

**Comment by priyanshuarora595** [comment]
If i use platform id as 00001659 and device id as 16590000

I get graphics acceleration but on hdmi external monitor and not on internal laptop screen

But if i use platform id 00001659 with device id 16190000 , i get no hardware acceleration but internal display works (with much lag) and hdmi doesn't work

Can this be helpful in finding the issue???

**Comment by priyanshuarora595** [comment]
Any idea ????
@symabbas

**Comment by symabbas** [comment]
I have a 5577 i7 model. And I worked on this EFI almost 5 months ago to get the hdmi working because that was the only thing not working at the time. If you haven't changed anything in the config file of the EFI I sent you, and the internal display still doesn't work, then may be you should try with a different SMBIOS. Preferably this one:
![Screenshot 2021-04-06 at 1 18 24 PM](https://user-images.githubusercontent.com/51963209/113677493-44ba5b00-96db-11eb-888e-56ae48786b46.png)

**Comment by symabbas** [comment]
or the MacbookPro14,1

**Comment by symabbas** [comment]
BTW I've got almost everything working here, except the subwoofer and WiFi

**Comment by symabbas** [comment]
is the internal display blank even without connecting the external monitor?

**Comment by symabbas** [comment]
Your HDMI to VGA thing might be an issue

**Comment by priyanshuarora595** [comment]
> I have a 5577 i7 model. And I worked on this EFI almost 5 months ago to get the hdmi working because that was the only thing not working at the time. If you haven't changed anything in the config file of the EFI I sent you, and the internal display still doesn't work, then may be you should try with a different SMBIOS. Preferably this one:
> ![Screenshot 2021-04-06 at 1 18 24 PM](https://user-images.githubusercontent.com/51963209/113677493-44ba5b00-96db-11eb-888e-56ae48786b46.png)

i have i5 model

**Comment by priyanshuarora595** [comment]
> is the internal display blank even without connecting the external monitor?

yess

**Comment by symabbas** [comment]
> i have i5 model

Try different SMBIOS

**Comment by priyanshuarora595** [comment]
> Your HDMI to VGA thing might be an issue

no its not... thats the only way by which i can see the screen 


other way is if i use device-id 16190000    but that does not have any graphics acceleration

**Comment by priyanshuarora595** [comment]
> > i have i5 model
> 
> Try different SMBIOS

which one

**Comment by symabbas** [comment]
MBPro14,1

**Comment by priyanshuarora595** [comment]
> MBPro14,1

ok let me try... but i have tried that earlier with no success.... but i'll try again..

**Comment by symabbas** [comment]
on the EFI that I sent you

**Comment by priyanshuarora595** [comment]
> on the EFI that I sent you

yeah i'll check it and get back to you...

**Comment by priyanshuarora595** [comment]
> MBPro14,1

Still the same 
![16176990974272677352763552045026](https://user-images.githubusercontent.com/57026241/113684996-6cadbc80-96e3-11eb-9dbb-77490410c5d8.jpg)

**Comment by symabbas** [comment]
Then you might have to do some experimentation of your own. I suggest you go through this page once (if you haven't) :
https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#kernel

If your existing installation is not too necessary, try reinstalling mac os using recovery if you have access to a LAN port. 
Or try making an installer from the current installation. This is my last bet.

**Comment by priyanshuarora595** [comment]
> Then you might have to do some experimentation of your own. I suggest you go through this page once (if you haven't) :
> https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/kaby-lake.html#kernel
> 
> If your existing installation is not too necessary, try reinstalling mac os using recovery if you have access to a LAN port.
> Or try making an installer from the current installation. This is my last bet.

I have used it no success
Thank you...

**Comment by priyanshuarora595** [comment]
Got it working

Just try this device properties :

AAPL,ig-platform-id
AAAbGQ==
device-id
FhkAAA==
disable-external-gpu
AQAAAA==
enable-hdmi20
AQAAAA==
framebuffer-con1-enable
AQAAAA==
framebuffer-con1-type
AAgAAA==
framebuffer-con2-busid
AAAAAA==
framebuffer-con2-enable
AQAAAA==
framebuffer-con2-flags
AAAAAA==
framebuffer-con2-index
/////w==
framebuffer-con2-pipe
AAAAAA==
framebuffer-con2-type
AQAAAA==
framebuffer-con3-enable
AQAAAA==
framebuffer-con3-flags
AAAAAA==
framebuffer-fbmem
AACQAA==
framebuffer-memorycount
AwAAAA==
framebuffer-patch-enable
AQAAAA==
framebuffer-pipecount
AwAAAA==
framebuffer-portcount
AwAAAA==
framebuffer-stolenmem
AAAwAQ==
framebuffer-unifiedmem
AAAAgA==
model
Intel HD Graphics 630

with boot args : -disablegfxfirmware lilucpu=8

Thank you
