### ISSUE TITLE
openCanopy Gui not working

### ISSUE THREAD

**Issue by priyanshuarora595** [Wmyaaa/Dell5577-hackintosh#36]
I want to change the boot picker . I want GUI boot picker but although openCanopy is present in EFI folder, still GUI is not working
please tell how to fix it and also how to get boot chime working
thank you

**Comment by Wmyaaa** [comment]
> 我想换靴子拾取器。我想GUI引导拾取器，但虽然打开Canopy是目前在EFI文件夹中，仍然GUI不工作
> ，请告诉如何修复它，也如何得到引导提示音工作
> 谢谢你

Maybe you can try another author's OC guide(https://github.com/wgggSg/OpenCore-For-DELL-5577). But when all the functions are normal, the laptop screen doesn't light up. Maybe you should reload the system

**Comment by priyanshuarora595** [comment]
> > 我想换靴子拾取器。我想GUI引导拾取器，但虽然打开Canopy是目前在EFI文件夹中，仍然GUI不工作
> > ，请告诉如何修复它，也如何得到引导提示音工作
> > 谢谢你
> 
> Maybe you can try another author's OC guide(https://github.com/wgggSg/OpenCore-For-DELL-5577). But when all the functions are normal, the laptop screen doesn't light up. Maybe you should reload the system

Ok

**Comment by Wmyaaa** [comment]
Re install the system

> > > 我想换靴子拾取器。我想GUI引导拾取器，但虽然打开Canopy是目前在EFI文件夹中，仍然GUI不工作
> > > ，请告诉如何修复它，也如何得到引导提示音工作
> > > 谢谢你
> > 
> > 
> > Maybe you can try another author's OC guide(https://github.com/wgggSg/OpenCore-For-DELL-5577). But when all the functions are normal, the laptop screen doesn't light up. Maybe you should reload the system
> 
> Ok

It's about re installing the system

**Comment by priyanshuarora595** [comment]
> Re install the system
> 
> > > > 我想换靴子拾取器。我想GUI引导拾取器，但虽然打开Canopy是目前在EFI文件夹中，仍然GUI不工作
> > > > ，请告诉如何修复它，也如何得到引导提示音工作
> > > > 谢谢你
> > > 
> > > 
> > > Maybe you can try another author's OC guide(https://github.com/wgggSg/OpenCore-For-DELL-5577). But when all the functions are normal, the laptop screen doesn't light up. Maybe you should reload the system
> > 
> > 
> > Ok
> 
> It's about re installing the system

I wont reinstall the system.... Can you tell which version of opencore is used in your latest release?

**Comment by Wmyaaa** [comment]
> > Re install the system
> > > > > 我想换靴子拾取器。我想GUI引导拾取器，但虽然打开Canopy是目前在EFI文件夹中，仍然GUI不工作
> > > > > ，请告诉如何修复它，也如何得到引导提示音工作
> > > > > 谢谢你
> > > > 
> > > > 
> > > > Maybe you can try another author's OC guide(https://github.com/wgggSg/OpenCore-For-DELL-5577). But when all the functions are normal, the laptop screen doesn't light up. Maybe you should reload the system
> > > 
> > > 
> > > Ok
> > 
> > 
> > It's about re installing the system
> 
> I wont reinstall the system.... Can you tell which version of opencore is used in your latest release?

I use the system version 11.2, OC has not been updated, or the end of the year of the rat version(鼠年完结版)

**Comment by priyanshuarora595** [comment]
> > > Re install the system
> > > > > > I want to change the boot picker. I want to boot the picker with GUI, but although opening Canopy is currently in the EFI folder, the GUI still doesn’t work 
> > > > > > , please tell me how to fix it and how to get the boot sound to work. 
> > > > > > Thank you
> > > > > 
> > > > > 
> > > > > Maybe you can try another author's OC guide( https://github.com/wgggSg/OpenCore-For-DELL-5577 ). But when all the functions are normal, the laptop screen doesn't light up. Maybe you should reload the system
> > > > 
> > > > 
> > > > Ok
> > > 
> > > 
> > > It's about re installing the system
> > 
> > 
> > I wont reinstall the system.... Can you tell which version of opencore is used in your latest release?
> 
> I use the system version 11.2, OC has not been updated, or the end of the year of the rat version

I am not asking system version , i am asking the opencore version you used.... 0.6.1-0.6.8 which one?
