### ISSUE TITLE
Battery drainage

### ISSUE THREAD

**Issue by priyanshuarora595** [Wmyaaa/Dell5577-hackintosh#37]
Battery is draining heavily
At max i can use it for 2 hours only
Please provide fix for it @Wmyaaa  @IITII 
Thanks

**Comment by priyanshuarora595** [comment]
![Screenshot 2021-04-10 at 6 22 32 PM](https://user-images.githubusercontent.com/57026241/114270475-34331900-9a2a-11eb-964b-081d4b6b00b4.png)
this is the report from intel power gadget . very high usage.
please guide to fix it

**Comment by priyanshuarora595** [comment]
Battery drained a lot while laptop was in sleep mode.  Also after wake up , the cpu was running at max frequency . 
How to fix it ? 
@IITII  @Wmyaaa

**Comment by Wmyaaa** [comment]
I know this problem exists, but I don't have time to fix it in my life. I will deal with it in my spare time




---Original---
From: ***@***.***&gt;
Date: Sun, Apr 11, 2021 13:49 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Wmyaaa/Dell5577-hackintosh] Battery drainage (#37)




 
Battery drained a lot while laptop was in sleep mode.  Also after wake up , the cpu was running at max frequency .
 How to fix it ?
 @IITII  @Wmyaaa

**Comment by priyanshuarora595** [comment]
> I know this problem exists, but I don't have time to fix it in my life. I will deal with it in my spare time
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Apr 11, 2021 13:49 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Wmyaaa/Dell5577-hackintosh] Battery drainage (#37) Battery drained a lot while laptop was in sleep mode. Also after wake up , the cpu was running at max frequency . How to fix it ? @IITII @Wmyaaa — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I have done a bit in it.  Disabled dgpu by ssdt patch , it gave a boost to battery . But after sleep its miserable. 

> I know this problem exists, but I don't have time to fix it in my life. I will deal with it in my spare time
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Apr 11, 2021 13:49 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Wmyaaa/Dell5577-hackintosh] Battery drainage (#37) Battery drained a lot while laptop was in sleep mode. Also after wake up , the cpu was running at max frequency . How to fix it ? @IITII @Wmyaaa — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


I have done a bit in it.  Disabled dgpu by ssdt patch , it gave a boost to battery . But after sleep its miserable.

**Comment by priyanshuarora595** [comment]
> I know this problem exists, but I don't have time to fix it in my life. I will deal with it in my spare time
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Apr 11, 2021 13:49 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Wmyaaa/Dell5577-hackintosh] Battery drainage (#37) Battery drained a lot while laptop was in sleep mode. Also after wake up , the cpu was running at max frequency . How to fix it ? @IITII @Wmyaaa — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.


I have done a bit in it.  Disabled dgpu by ssdt patch , it gave a boost to battery . But after sleep its miserable.

**Comment by priyanshuarora595** [comment]
> I know this problem exists, but I don't have time to fix it in my life. I will deal with it in my spare time



I have done a bit in it.  Disabled dgpu by ssdt patch , it gave a boost to battery . But after sleep its miserable.

**Comment by priyanshuarora595** [comment]
> I know this problem exists, but I don't have time to fix it in my life. I will deal with it in my spare time
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Sun, Apr 11, 2021 13:49 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [Wmyaaa/Dell5577-hackintosh] Battery drainage (#37) Battery drained a lot while laptop was in sleep mode. Also after wake up , the cpu was running at max frequency . How to fix it ? @IITII @Wmyaaa — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hey i figured it out. 
Its the audio which is causing this issue , as soon as i try to increase or decrease volume , the cpu frequency jumps to the max and it causes the whole mess. 
Now we know the culprit , we must solve it.  
Do you have any ideas?

**Comment by priyanshuarora595** [comment]
> > I know this problem exists, but I don't have time to fix it in my life. I will deal with it in my spare time
> > […](#)
> > ---Original--- From: _**@**_._**> Date: Sun, Apr 11, 2021 13:49 PM To: _**@**_.**_>; Cc: _**@**_._**_**@**_.**_>; Subject: Re: [Wmyaaa/Dell5577-hackintosh] Battery drainage (#37) Battery drained a lot while laptop was in sleep mode. Also after wake up , the cpu was running at max frequency . How to fix it ? @IITII @Wmyaaa — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> Hey i figured it out.
> Its the audio which is causing this issue , as soon as i try to increase or decrease volume , the cpu frequency jumps to the max and it causes the whole mess.
> Now we know the culprit , we must solve it.
> Do you have any ideas?

Fixed it by changing alcid to 5 . Thank you
