### ISSUE TITLE
Mac OS 10.15 Beta

### ISSUE THREAD

**Issue by shixinwu** [Wmyaaa/Dell5577-hackintosh#4]
更新Mac OS 10.15 Beta安装失败，显示五国

**Comment by Wmyaaa** [comment]
> 更新Mac OS 10.15 Beta安装失败，显示五国

安装最好用包内的引导，记得更换clover引导，-V

**Comment by Wmyaaa** [comment]
> 更新Mac OS 10.15 Beta安装失败，显示五国

目前我正在弄5577的15引导，目前在测试。过两天会放出来。
