### ISSUE TITLE
向下兼容  独显

### ISSUE THREAD

**Issue by oxwo** [Wmyaaa/Dell5577-hackintosh#7]
这个能不能装10.13.6   想在10.13独显可以吗

感谢🙏这个项目太伟大了🙏

**Comment by Wmyaaa** [comment]
除非你的电脑支持独显输出功能，否则没有办法启用独显

**Comment by oxwo** [comment]
那个supportAssist怎么卸载  每次重启都会出来

**Comment by Wmyaaa** [comment]
开机显supportAssist可以Esc跳过。关闭的话百度上好像有教程。当你不再修改引导分区的时候它就不会再跳出来了😂。

**Comment by oxwo** [comment]
网上大部分都是在新版bios上修改 而dell5577是老版bios网上没找到

**Comment by Wmyaaa** [comment]
以dell i5-7560为例：
开机按F2，进入BIOS，
在General－advanced boot options里【enable legacy option roms】打勾
在Secure boot—expert key management里选择 disablde，
选apply—OK保存 ，
在General—boot list option里选择 legacy，
在General—boot sequence里移动 intemal hdd 到顶部，
选apply—OK—exit退出 ，
这样supportassist就不会开机启动了。
-------------------------------------------------------------------
转自百度知道
不知道能不能行😂

**Comment by oxwo** [comment]
不知道你是怎么关的

**Comment by Wmyaaa** [comment]
我没有关他。supportAssist就像你楼底下的保安。你每天走他面前过，他肯定不会拦你。你更换引导或者调动了其他底层的东西，就像你带个面具或者其他人要走保安面前过，他就要喊你做记录一样。🙂

**Comment by oxwo** [comment]
好的 谢谢大佬的回复👍 给你一个star🌟

**Comment by Wmyaaa** [comment]
都是慢慢玩过来的，哪有什么大佬。哈哈哈哈哈哈哈

**Comment by oxwo** [comment]
👍
